In [1]:
import requests
import pandas as pd
import numpy as np

def financial_statement(year, season, type='綜合損益彙總表'):

    if year >= 1000:
        year -= 1911

    if type == '綜合損益彙總表':
        url = 'https://mops.twse.com.tw/mops/web/ajax_t163sb04'
    elif type == '資產負債彙總表':
        url = 'https://mops.twse.com.tw/mops/web/ajax_t163sb05'
    elif type == '營益分析彙總表':
        url = 'https://mops.twse.com.tw/mops/web/ajax_t163sb06'
    else:
        print('type does not match')

    r = requests.post(url, {
        'encodeURIComponent':1,
        'step':1,
        'firstin':1,
        'off':1,
        'TYPEK':'sii',
        'year':str(year),
        'season':str(season),
    })

    r.encoding = 'utf8'
    dfs = pd.read_html(r.text, header=None)
    return dfs
#     return pd.concat(dfs[1:], axis=0, sort=False)\
#              .set_index(['公司代號'])\
#              .apply(lambda s: pd.to_numeric(s, errors='ceorce'))

In [14]:
# financial_statement(2022,1,'綜合損益彙總表')[1]

,公司代號,公司名稱,利息淨收益,利息以外淨損益,呆帳費用、承諾及保證責任準備提存,營業費用,繼續營業單位稅前淨利（淨損）,所得稅費用（利益）,繼續營業單位本期稅後淨利（淨損）,停業單位損益,...,其他綜合損益（稅後）,合併前非屬共同控制股權綜合損益淨額,本期綜合損益總額（稅後）,淨利（損）歸屬於母公司業主,淨利（損）歸屬於共同控制下前手權益,淨利（損）歸屬於非控制權益,綜合損益總額歸屬於母公司業主,綜合損益總額歸屬於共同控制下前手權益,綜合損益總額歸屬於非控制權益,基本每股盈餘（元）
0,2801,彰銀,5451252,1978438,557306,4053988,2818396,441254,2377142,--,...,-764318,--,1612824,2377142,--,--,1612824,--,--,0.23
1,2809,京城銀,1462149,-861601,-80904,484973,196479,159838,36641,--,...,-2078362,--,-2041721,36641,--,--,-2041721,--,--,0.03
2,2812,台中銀,2417616,1019878,217869,1657132,1562493,286479,1276014,--,...,-168249,--,1107765,1276014,--,--,1107765,--,--,0.28
3,2820,華票,299718,302994,-19563,121286,500989,74047,426942,--,...,-1468419,0,-1041477,--,--,--,--,--,--,0.32
4,2834,臺企銀,4691032,1521781,255260,3368433,2589120,464859,2124261,0,...,-1266542,--,857719,2124261,0,0,857719,0,0,0.27
5,2836,高雄銀,682808,352471,68326,656025,310928,31399,279529,--,...,-676271,--,-396742,--,--,--,--,--,--,0.24
6,2838,聯邦銀,2330496,1141123,137734,2524449,809436,225402,584034,--,...,-2636463,--,-2052429,583177,--,857,-2053286,--,857,0.19
7,2845,遠東銀,1623026,923109,207087,1588196,750852,90140,660712,--,...,-639091,--,21621,660712,--,--,21621,--,--,0.19
8,2849,安泰銀,958250,604291,93172,710011,759358,78419,680939,0,...,-806262,--,-125323,--,--,--,--,--,--,0.35
9,2897,王道銀行,1200418,1096626,43812,1134712,1118520,233590,884930,7471,...,-2037979,--,-1145578,581783,--,310618,-412423,--,-733155,0.21
10,5876,上海商銀,6749977,3278520,440332,3932966,5655199,1085510,4569689,--,...,-4432720,--,136969,3640800,--,928889,-117241,--,254210,0.81

In [15]:
# financial_statement(2022,1,'資產負債彙總表')[1]

,公司代號,公司名稱,現金及約當現金,存放央行及拆借銀行同業,透過損益按公允價值衡量之金融資產,透過其他綜合損益按公允價值衡量之金融資產,按攤銷後成本衡量之債務工具投資,避險之衍生金融資產淨額,附賣回票券及債券投資淨額,應收款項－淨額,...,庫藏股票,歸屬於母公司業主之權益合計,共同控制下前手權益,合併前非屬共同控制股權,非控制權益,權益總額,待註銷股本股數（單位：股）,母公司暨子公司所持有之母公司庫藏股股數（單位：股）,預收股款（權益項下）之約當發行股數（單位：股）,每股參考淨值
0,2801,彰銀,28692563,216088890,87639414,198358217,419118658,0,--,21023890,...,0,173065279,--,--,--,173065279,--,0,0,16.50
1,2809,京城銀,3190973,11484372,41449946,43684558,18499021,--,0,9592546,...,0,46839307,0,--,0,46839307,0,0,0,41.77
2,2812,台中銀,14287370,41734407,34128834,49998783,109314388,--,11392750,14434145,...,0,64567750,--,--,0,64567750,0,0,0,14.23
3,2820,華票,290685,500000,108520693,100656867,--,--,4214167,788646,...,--,--,--,--,--,24517224,0,0,0,18.26
4,2834,臺企銀,27640735,146057016,40299039,168342848,282491269,--,19176457,8102224,...,0,102517691,0,--,0,102517691,0,0,0,13.24
5,2836,高雄銀,3821173,9698761,400811,33198422,50820356,--,8026610,1062515,...,--,--,--,--,--,17278405,0,0,0,14.36
6,2838,聯邦銀,8001887,25924703,57865453,70394890,80679368,--,32442005,25209772,...,--,63082025,--,--,844615,63926640,--,0,0,18.05
7,2845,遠東銀,4486164,39843279,43378449,106134927,68136263,--,2600390,19414935,...,--,49723572,--,--,--,49723572,--,0,0,14.15
8,2849,安泰銀,1869396,12995742,14893600,43917490,37552296,--,2514296,3316508,...,-5175,--,--,--,--,34709919,300701,300701,0,17.73
9,2897,王道銀行,8493631,12104523,149466133,185663075,--,--,4214167,20084459,...,-16837,35996248,--,--,18054413,54050661,--,2522000,0,11.88
10,5876,上海商銀,60994662,275978795,8433721,522759443,136479322,--,287750,14693220,...,-83144,157684575,--,--,51690594,209375169,--,11397439,0,35.27

In [12]:
# financial_statement(2022,1,'營益分析彙總表')[0]

,0,1,2,3,4,5,6
0,公司代號,公司名稱,營業收入(百萬元),毛利率(%)(營業毛利)/(營業收入),營業利益率(%)(營業利益)/(營業收入),稅前純益率(%)(稅前純益)/(營業收入),稅後純益率(%)(稅後純益)/(營業收入)
1,1101,台泥,22973.46,8.69,0.90,5.10,3.73
2,1102,亞泥,19681.12,15.12,12.52,17.45,13.80
3,1103,嘉泥,512.58,2.99,-19.56,-10.00,-15.07
4,1104,環泥,1532.25,19.07,11.21,37.31,35.14
...,...,...,...,...,...,...,...
994,9944,新麗,713.72,29.18,8.66,11.83,8.61
995,9945,潤泰新,6290.19,24.59,16.77,63.66,63.02
996,9946,三發地產,209.38,30.31,12.33,9.06,7.43
997,9955,佳龍,382.09,1.72,-4.84,-4.08,-4.08
998,9958,世紀鋼,2223.65,22.41,19.46,22.71,18.14